#!/bin/sh

PRG="$0"

LIBPREFIX=/usr/lib/mysql-gui
export MQB_DIR=/usr
export LD_LIBRARY_PATH=$LIBPREFIX:$LD_LIBRARY_PATH
export GDK_PIXBUF_MODULE_FILE=$LIBPREFIX/gdk-pixbuf.loaders
export PANGO_RC_FILE=$LIBPREFIX/pangorc
export GTK_EXE_PREFIX=$LIBPREFIX

$PRG-bin $args

